- template: alertmanager
- template: alloy
- template: cert-manager
- template: cilium
- template: envoy-gateway
- template: dynamic-dns
- template: external-dns
- template: external-snapshotter
- template: flux-bootstrap
  flux: false
- template: gateway
- template: gateway-api
- template: gateway-route-sync
- template: grafana
- template: grafana-operator
- template: kube-state-metrics
- template: linstor
- template: loki
- template: metrics-server
- template: minecraft
- template: minio
- template: minio-operator
- template: minio-operator-ext
- template: monitoring-config
- template: network-policy
- template: piraeus-operator
- template: postfix
- template: prometheus
- template: prometheus-node-exporter
- template: prometheus-operator
- template: pvc-restore
- template: router-policy-sync
- template: storage-class
- template: vault
- template: vault-push-secrets
- template: vault-secrets-operator
- template: vertical-pod-autoscaler
- template: volsync
- template: volsync-testing
- template: volume-snapshot-api
